### ISSUE TITLE
integron_finder error

### ISSUE THREAD

**Issue by ramadatta** [xthua/bacant#4]
Hi @xthua ,

Sorry to bother again. After the bacant update to v3.3.4, I get the integron_finder error. 

I do not see the annotation.tsv file in the results folder either. This was not a problem in v3.3.3.

I have create a new environment with bacant v3.3.4, but with no success.

```
$ conda create -n bacant2

$ conda activate bacant2

$ conda install -c bacant -c conda-forge -c bioconda bacant

$ time bacant -n filename.fasta -o filename_bacant_out
Analysing file /home/user/filename.fasta  at 2022-09-02 12:10:32
replicon search done
integron_finder error
AMR done
transposon done
All Done  at 2022-09-02 12:10:59
```
may I know if I am missing something.

**Comment by xthua** [comment]
Hi, please try to re-install 3.3.4. it may solve the problem.

Best wishes,

Xiaoting



-----原始邮件-----
发件人:"Prakki Rama" ***@***.***>
发送时间:2022-09-02 12:15:21 (星期五)
收件人: xthua/bacant ***@***.***>
抄送: "Xiaoting Hua" ***@***.***>, Mention ***@***.***>
主题: [xthua/bacant] integron_finder error (Issue #4)






Hi @xthua ,

Sorry to bother again. After the bacant update to v3.3.4, I get the integron_finder error.

I do not see the annotation.tsv file in the results folder either. This was not a problem in v3.3.3.

I have create a new environment with bacant v3.3.4, but with no success.

time bacant -n filename.fasta -o filename_bacant_out
Analysing file /home/user/filename.fasta  at 2022-09-02 12:10:32
replicon search done
integron_finder error
AMR done
transposon done
All Done  at 2022-09-02 12:10:59 

may I know if I am missing something.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>





Xiaoting Hua, PhD, Associate Professor
Sir Run Run Shaw Hospital, Zhejiang University School of Medicine,
Qingchundong 3 RD,
Hangzhou 310016, 
China

**Comment by ramadatta** [comment]
Hi, I tried install the package in new conda environment with the latest version available in conda. But, still the integron_finder error is not resolved. Thanks.

**Comment by xthua** [comment]
Did you use the previous fasta file? We tested the fasta file in several machines, and it’s ok.Best wishes Xiaoting ---- Replied Message ----FromPrakki ***@***.***>Date09/08/2022 13:27 ***@***.***> CcXiaoting ***@***.******@***.***>SubjectRe: [xthua/bacant] integron_finder error (Issue #4)
Hi, I tried install the package in new conda environment with the latest version available in conda. But, still the integron_finder error is not resolved. Thanks.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/xthua/bacant/issues/4#issuecomment-1240235911",
"url": "https://github.com/xthua/bacant/issues/4#issuecomment-1240235911",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ramadatta** [comment]
Hi @xthua 

Thanks, strangely it still did not work on my system but worked on other system.
Looks like some issue with dependencies in my system even with fresh installation in conda environment. 

Anyway, thank you so much for your kind help!
