### ISSUE TITLE
assembly draft visulization problem

### ISSUE THREAD

**Issue by aslangabriel** [xthua/bacant#5]
hi，I have tested bacant with genomic assembly drafts, however there w no html files created. Would you like to help me with this issue?
Thanks a lot.

**Comment by xthua** [comment]
Hi, do you use the web server or the standalone version? also, would you like to provide the test file?

Best wishes,
Xiaoting



-----原始邮件-----
发件人:aslangabriel ***@***.***>
发送时间:2022-10-26 09:15:14 (星期三)
收件人: xthua/bacant ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SPAM] [xthua/bacant] assembly draft visulization problem (Issue #5)






hi，I have tested bacant with genomic assembly drafts, however there w no html files created. Would you like to help me with this issue?
Thanks a lot.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>





Xiaoting Hua, PhD, Associate Professor
Sir Run Run Shaw Hospital, Zhejiang University School of Medicine,
Qingchundong 3 RD,
Hangzhou 310016, 
China
